config/routes.rb
Rails.application.routes.draw do

  get 'posts/index' => 'posts#index', as: "board"

  get 'posts/new'

  get 'posts/create'

  get 'posts/show'

  get 'posts/edit'

  get 'posts/update'

  get 'posts/delete'

  get 'messages/index' => 'messages#index', as: 'messages'

  get 'messages/new' => 'messages#new', as: 'new_message'

  post 'messages/new' => 'messages#new', as: 'start_message'

  post 'messages/create' => 'messages#create', as: 'send_message'

  get 'messages/show' 

  get 'messages/edit'

  get 'messages/update'

  get 'messages/delete'

  get 'depts/index'

  get 'depts/new'

  post 'depts/create' => 'depts#create', as: 'new_dept'

  get 'depts/show'

  get 'depts/edit'

  post 'depts/update' => 'depts#update', as: 'add_emps'

  delete 'depts/delete' => 'depts#delete', as: 'delete_dept'

  delete 'depts/reassign' => 'depts#reassign', as: 'reassign_emp'

  get 'supervisions/index'

  get 'supervisions/new'

  post 'supervisions/create' => 'supervisions#create', as: 'promote'

  get 'supervisions/show'

  get 'supervisions/edit'

  get 'supervisions/update'

  delete 'supervisions/delete' => 'supervisions#delete', as: 'demote'

  get 'santa/index' => 'santa#index', as: 'santas'

  get 'santa/new'

  post 'santa/create' => 'santa#create', as: 'assign_santas'

  get 'santa/show' => 'santa#show', as: 'santa'

  get 'santa/edit'

  get 'santa/update'

  delete 'santa/delete' => 'santa/delete', as: 'destroy_santas'

  root 'users#new'
  
  get 'friendships/index' => 'friendships#index', as: 'friends'

  get 'friendships/new'

  post 'friendships/create' => 'friendships#create', as: "add_friend"

  get 'friendships/show'

  get 'friendships/edit'

  get 'friendships/update'

  delete 'friendships/delete' => 'friendships#delete', as: 'remove_friend'

  get 'sessions/index'

  get 'login' => 'sessions#new', as: 'login_page'

  post 'login' => 'sessions#create', as: 'login'

  get 'sessions/show'

  get 'sessions/edit'

  get 'sessions/update'

  delete 'logout' => 'sessions#destroy', as: 'logout'

  get 'wishes/index'

  get 'wishes/new'

  post 'wishes/create' => 'wishes#create', as: 'add_wish'

  get 'wishes/create' => 'wishes#create', as: 'new_wish'

  get 'wishes/show'

  get 'wishes/edit'

  get 'wishes/update'

  delete 'wishes/delete' => 'wishes#delete', as: 'remove_item'

  get 'items' =>  'items#index', as: 'items'

  get 'items/new'

  post 'items/create' => 'items#create', as: 'create_item'

  get 'items/show' => 'items#show', as: 'view_item'

  get 'items/edit'

  get 'items/update'

  get 'items/delete'

  get 'users' => 'users#index', as: 'users'

  get 'register' => 'users#new', as: 'register_page'

  post 'register' => 'users#create', as: 'register'

  get 'showuser' => 'users#show', as: 'user'

  get 'users/edit' => 'users#edit', as: 'edit_user'

  patch 'users/update' => 'users#update', as: 'update_user'

  get 'users/delete'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/dept.rb
class Dept < ActiveRecord::Base
	has_many :users, dependent: :nullify
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, foreign_key: :friend_id, class_name: User
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :wishes, foreign_key: :wisher_id
  has_many :wishers, through: :wishes, source: :wisher
  has_many :comments, as: :commentable
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
end

app/models/pm.rb
class Pm < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/santum.rb
class Santum < ActiveRecord::Base
  belongs_to :gifter, foreign_key: :gifter_id, class_name: 	User
  belongs_to :giftee, foreign_key: :giftee_id, class_name: User
end

app/models/supervision.rb
class Supervision < ActiveRecord::Base
  belongs_to :lead, foreign_key: :lead_id, class_name: User
  belongs_to :dr, foreign_key: :dr_id, class_name: User
end

app/models/user.rb
class User < ActiveRecord::Base
  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]+)\z/i
  has_secure_password
  validates :firstname, :lastname, :email, presence: :true
  validates :email, uniqueness: :true, format: {with: email_regex}
  before_save :downcase_email


  has_many :items
  belongs_to :dept
  has_many :comments, as: :commentable


  has_many :wishes, foreign_key: :wisher_id
  has_many :wished_fors, through: :wishes, source: :wished_for


  has_many :friendships, foreign_key: :user_id
  has_many :friends, through: :friendships, source: :friend

  has_many :relationships, foreign_key: :friend_id, class_name: "Friendship"
  has_many :users, through: :relationships, source: :user


  has_many :santa, foreign_key: :gifter_id
  has_many :giftees, through: :santa, source: :giftee

  has_many :assigned, foreign_key: :giftee_id, class_name: "Santum"
  has_many :gifters, through: :assigned, source: :gifter


  has_many :supervisions, foreign_key: :lead_id
  has_many :drs, through: :supervisions, source: :dr

  has_many :monitors, foreign_key: :dr_id, class_name: "Supervision"
  has_many :leads, through: :monitors, source: :lead


  has_many :messages, foreign_key: :recipient_id
  has_many :senders, through: :messages, source: :sender

  has_many :missives, foreign_key: :sender_id, class_name: "Message"
  has_many :recipients, through: :missives, source: :recipient



  def downcase_email
  	self.email.downcase!
  end 

  def update_user(params)
    user = User.find(current_user.id)
    user.firstname = params[:firstname]
    user.lastname = params[:lastname]
    user.email = params[:email]
    user.location = params[:location]
    user.country = params[:country]
    user.save
    return user
  end 

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :wisher, foreign_key: :wisher_id, class_name: User
  belongs_to :wished_for, foreign_key: :wished_for_id, class_name: Item
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if not current_user.level == "admin"
      return redirect_to index_path 
    end  
    @users = User.all.where.not(id: current_user.id)

    @depts = Dept.all

    @employees = User.all.where(dept: nil)

    @regs = User.all.where(level: "reg")
    @people = @regs.where.not(dept: nil)
  end

  def new
    if current_user
      return redirect_to items_path
    end  
    @countries = ["US", "TX", "UK", "CH", "CAN", "DE", "FR", "DM", "SW", "IT", "KE", "SA"]
  end

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      session[:user_id]= user.id
      return redirect_to items_path
    end
    flash[:errors] = user.errors.full_messages    
    return redirect_to :back
  end

  def show
    @user = User.find(params[:user_id])
    @items = @user.wished_fors.all
    return render "/users/show.html.erb"
  end 

  def edit
    @countries = ["US", "TX", "UK", "CH", "CAN", "DE", "FR", "DM", "SW", "IT", "KE", "SA"]
  end

  def update
    user = update_user(user_params)
    if user.valid?
      user.save
    end  
    return redirect_to items_path
  end

  def delete
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :location, :country, :password, :password_confirmation)
    end 

    def update_user(params)
    user = User.find(current_user.id)
    user.firstname = params[:firstname]
    user.lastname = params[:lastname]
    user.email = params[:email]
    user.dob = params[:dob]
    user.country = params[:country]
    user.save
    return user
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/p_ms_helper.rb
module PMsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/santa_helper.rb
module SantaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/supervisions_helper.rb
module SupervisionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div class="row green">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>	

			<h2> Profile for <%= current_user.firstname %></h2>

			<form class="form" action="<%= update_user_path %>" method="post">

			<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
			<input type="hidden" name="_method" value="patch">

				<p>First Name:<input type="text" name="user[firstname]" value="<%= current_user.firstname %>"></p>
				<p>Last Name:<input type="text" name="user[lastname]" value="<%= current_user.lastname %>"></p>
				<p>Email:<input type="text" name="user[email]" value="<%= current_user.email %>"></p>
				<p>Country:<select name="user[country]">
								<option value="<%= current_user.country %>"><%= current_user.country %></option>
								<% @countries.each do |country| %>
								<option value="<%= country %>"><%= country %></option><% end %></select></p>
				<p><button class="other-buttons" type="submit">Register</button></p>

			</form>
	</div>
	<div class="col-sm-4"></div>
</div>				

app/views/users/index.html.erb
<div class="row darkgreen text-center">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>			
			<h2>All Users</h2>
	</div>
	<div class="col-sm-4"></div>
</div>			



<div class="row green">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>	

						<% if @depts %>
						<% @depts.each do |dept| %>
						<h2> <%= dept.name %></h2>
						<table class="contents">
							<thead>
								<tr>
									<th>Name</th>
									<th>Level</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
							<% if dept.users %>
							<% dept.users.each do |emp| %>
								<tr>
									<td><%= emp.firstname %> <%= emp.lastname %></td>
									<td><%= emp.level %></td>
									<% if emp.level == "reg" %>
									<td><%= link_to "Reassign", reassign_emp_path(id: emp.id), method: :delete %> | 
										<%= link_to "Promote", promote_path(id: emp.id), method: :post %> </td>
									<% elsif emp.level == "lead" %>
									<td><%= link_to "Demote", demote_path(id: emp.id), method: :delete %></td> 
									<% end %>
								</tr>
							<% end %>
							<% end %>
							</tbody>
						</table>
						<br>
						<p class="red"> <%= link_to "Disband", delete_dept_path(id: dept.id), method: :delete %> </p>	
						<p> ----------------------------------------------------------</p>
						<% end %>
						<% end %>	
	</div>
	<div class="col-sm-4"></div>
</div>						


















<div class="row darkgreen">
	<div class="col-sm-4"></div>
	<div class='col-sm-4 text-right'>	

			<h3> Create Department </h3>
			<form class="form" action="/depts/create" method="post">
			<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
			<p><input type="text" name="newdept" placeholder="New Department Name"></p>	
			<button type="submit">Create</button>
			</form>

	</div>
	<div class="col-sm-4"></div>
</div>



<div class="row green">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>

			<h3> Add Employee to Department</h3>
			<form class="form" action="/depts/update" method="post">
			<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
			<h4> 1. Select Employee </h4>
				<% if @employees %>
				<% @employees.each do |emp| %>
					<p><input type="checkbox" name="emp[]" value="<%= emp.id %>"> <%= emp.firstname %> <%= emp.lastname %></p>
				<% end %>
				<% end %>
			</select>
			<h4> 2. Select Department </h4>
			<select name="dept">
				<% if @depts %>
				<% @depts.each do |dept| %>
					<option value="<%= dept.id %>"><%= dept.name %></option>
				<% end %>
				<% end %>
			</select>
			<br>
			<br>
			<p><button class="other-buttons" type="submit">Add</button></p>
			</form>
	</div>		
	<div class="col-sm-4"></div>
</div>



<div class="row darkgreen text-right">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>

			<h3> Quick Promotion </h3>
			<form class="form" action="/supervisions/create" method="post">
			<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
			<p> Select Employee to Promote </p>
			<select name="id">
				<% if @people %>
				<% @people.each do |emp|%>
					<option value="<%= emp.id %>"><%= emp.firstname %> <%= emp.lastname %> -- <%= emp.dept.name %></option>
				<% end %>
				<% end %>	
			</select>
			<p><p><button type="submit">Promote</button></p></p>
			</form>
	</div>
	<div class="col-sm-4"></div>
</div>			

			

app/views/users/new.html.erb
<div class="row green">
	<div class="col-sm-4"></div>
	<div class='col-sm-4'>

		<p><em>Welcome to kkneville's SecretSanta app. To see this app in action, please register as a character from the Harry Potter universe, and take a look.</em></p>

		<p><em>For full functionality, you will need to log in as Albus Dumbledore (albus@dumbledore.com, password1).</em></p>

		<h1>Register</h1>
  		<p>Please register to join our community.</p> 

		<form class="form" action="register" method="post">
		<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
			
			
				<p><input type="text" name="user[firstname]" placeholder="First Name"></p>
				
				<p><input type="text" name="user[lastname]" placeholder="Last Name"></p>
					
				<p><input type="email" name="user[email]" placeholder="Email"></p>
			
				<p><input type="password" name="user[password]" placeholder="Password"></p>
						
				<p><input type="password" name="user[password_confirmation]" placeholder="Confirm Password"></p>	
			
			<button class="other-buttons" type="submit">Register</button>	
		</form>
	</div>
	<div class="col-sm-4"></div>
</div>	

app/views/users/show.html.erb
<div class="row darkgreen">
	<div class="col-sm-4"></div>
	<div class="col-sm-4 contents">
		<h2><%= @user.firstname %> <%= @user.lastname %>'s Profile </h2>
			<p> Name: <%= @user.firstname %> <%= @user.lastname %> </p>
			<p> Level: <%= @user.level %></p>
			<p> House: 
				<% if @user.dept %>
					<%= @user.dept.name %>
				<% end %>
			</p>


			<p><% if @user == current_user %>
			<%= link_to "Edit", edit_user_path(id: current_user.id) %>
			<% end %></p>
	</div>
	<div class="col-sm-4"></div>
</div>			


<div class="row green">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">
	<h3> <%= @user.firstname %> <% @user.lastname %>'s Wishlist </h3>

	<ul class="contents">
		<% @items.each do |item| %>
		<li> <%= item.name %> : <%= item.price %> 
			<% if @user == current_user%> | <%= link_to "Remove", remove_item_path(:id => item.id), :method => :delete %> <% end %>
		</li>
		<% end %>
	</ul>
	</div>
	<div class="col-sm-4"></div>	
</div>	

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>