config/routes.rb
Rails.application.routes.draw do

  get 'posts/index' => 'posts#index', as: "board"

  get 'posts/new'

  get 'posts/create'

  get 'posts/show'

  get 'posts/edit'

  get 'posts/update'

  get 'posts/delete'

  get 'messages/index' => 'messages#index', as: 'messages'

  get 'messages/new' => 'messages#new', as: 'new_message'

  post 'messages/new' => 'messages#new', as: 'start_message'

  post 'messages/create' => 'messages#create', as: 'send_message'

  get 'messages/show' 

  get 'messages/edit'

  get 'messages/update'

  get 'messages/delete'

  get 'depts/index'

  get 'depts/new'

  post 'depts/create' => 'depts#create', as: 'new_dept'

  get 'depts/show'

  get 'depts/edit'

  post 'depts/update' => 'depts#update', as: 'add_emps'

  delete 'depts/delete' => 'depts#delete', as: 'delete_dept'

  delete 'depts/reassign' => 'depts#reassign', as: 'reassign_emp'

  get 'supervisions/index'

  get 'supervisions/new'

  post 'supervisions/create' => 'supervisions#create', as: 'promote'

  get 'supervisions/show'

  get 'supervisions/edit'

  get 'supervisions/update'

  delete 'supervisions/delete' => 'supervisions#delete', as: 'demote'

  get 'santa/index' => 'santa#index', as: 'santas'

  get 'santa/new'

  post 'santa/create' => 'santa#create', as: 'assign_santas'

  get 'santa/show' => 'santa#show', as: 'santa'

  get 'santa/edit'

  get 'santa/update'

  delete 'santa/delete' => 'santa/delete', as: 'destroy_santas'

  root 'users#new'
  
  get 'friendships/index' => 'friendships#index', as: 'friends'

  get 'friendships/new'

  post 'friendships/create' => 'friendships#create', as: "add_friend"

  get 'friendships/show'

  get 'friendships/edit'

  get 'friendships/update'

  delete 'friendships/delete' => 'friendships#delete', as: 'remove_friend'

  get 'sessions/index'

  get 'login' => 'sessions#new', as: 'login_page'

  post 'login' => 'sessions#create', as: 'login'

  get 'sessions/show'

  get 'sessions/edit'

  get 'sessions/update'

  delete 'logout' => 'sessions#destroy', as: 'logout'

  get 'wishes/index'

  get 'wishes/new'

  post 'wishes/create' => 'wishes#create', as: 'add_wish'

  get 'wishes/create' => 'wishes#create', as: 'new_wish'

  get 'wishes/show'

  get 'wishes/edit'

  get 'wishes/update'

  delete 'wishes/delete' => 'wishes#delete', as: 'remove_item'

  get 'items' =>  'items#index', as: 'items'

  get 'items/new'

  post 'items/create' => 'items#create', as: 'create_item'

  get 'items/show' => 'items#show', as: 'view_item'

  get 'items/edit'

  get 'items/update'

  get 'items/delete'

  get 'users' => 'users#index', as: 'users'

  get 'register' => 'users#new', as: 'register_page'

  post 'register' => 'users#create', as: 'register'

  get 'showuser' => 'users#show', as: 'user'

  get 'users/edit' => 'users#edit', as: 'edit_user'

  patch 'users/update' => 'users#update', as: 'update_user'

  get 'users/delete'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/dept.rb
class Dept < ActiveRecord::Base
	has_many :users, dependent: :nullify
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, foreign_key: :friend_id, class_name: User
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :wishes, foreign_key: :wisher_id
  has_many :wishers, through: :wishes, source: :wisher
  has_many :comments, as: :commentable
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
end

app/models/pm.rb
class Pm < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/santum.rb
class Santum < ActiveRecord::Base
  belongs_to :gifter, foreign_key: :gifter_id, class_name: 	User
  belongs_to :giftee, foreign_key: :giftee_id, class_name: User
end

app/models/supervision.rb
class Supervision < ActiveRecord::Base
  belongs_to :lead, foreign_key: :lead_id, class_name: User
  belongs_to :dr, foreign_key: :dr_id, class_name: User
end

app/models/user.rb
class User < ActiveRecord::Base
  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]+)\z/i
  has_secure_password
  validates :firstname, :lastname, :email, presence: :true
  validates :email, uniqueness: :true, format: {with: email_regex}
  before_save :downcase_email


  has_many :items
  belongs_to :dept
  has_many :comments, as: :commentable


  has_many :wishes, foreign_key: :wisher_id
  has_many :wished_fors, through: :wishes, source: :wished_for


  has_many :friendships, foreign_key: :user_id
  has_many :friends, through: :friendships, source: :friend

  has_many :relationships, foreign_key: :friend_id, class_name: "Friendship"
  has_many :users, through: :relationships, source: :user


  has_many :santa, foreign_key: :gifter_id
  has_many :giftees, through: :santa, source: :giftee

  has_many :assigned, foreign_key: :giftee_id, class_name: "Santum"
  has_many :gifters, through: :assigned, source: :gifter


  has_many :supervisions, foreign_key: :lead_id
  has_many :drs, through: :supervisions, source: :dr

  has_many :monitors, foreign_key: :dr_id, class_name: "Supervision"
  has_many :leads, through: :monitors, source: :lead


  has_many :messages, foreign_key: :recipient_id
  has_many :senders, through: :messages, source: :sender

  has_many :missives, foreign_key: :sender_id, class_name: "Message"
  has_many :recipients, through: :missives, source: :recipient



  def downcase_email
  	self.email.downcase!
  end 

  def update_user(params)
    user = User.find(current_user.id)
    user.firstname = params[:firstname]
    user.lastname = params[:lastname]
    user.email = params[:email]
    user.location = params[:location]
    user.country = params[:country]
    user.save
    return user
  end 

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :wisher, foreign_key: :wisher_id, class_name: User
  belongs_to :wished_for, foreign_key: :wished_for_id, class_name: Item
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    q1 = current_user.friends
    q2 = current_user.users
    @friends = q1 + q2
    @people = User.where.not(id: @friends)
    @people = @people.where.not(id: current_user.id)
  end

  def new
  end

  def create
    friendship = Friendship.new
    friendship.user = current_user
    friendship.friend = User.find(params[:id])
    friendship.save
    return redirect_to friends_path
  end

  def show
  end

  def edit
      
  end

  def update
  end

  def delete
    friendships1 = Friendship.where(friend_id: params[:user_id])
    puts friendships1
    friendships2 = Friendship.where(user_id: params[:user_id])
    puts friendships2
    @friendships = friendships1 + friendships2
    @friendships.each do |fs| 
      if fs.user_id == current_user.id 
        fs.delete
        return redirect_to friends_path
      elsif fs.friend_id == current_user.id
        fs.delete
        return redirect_to friends_path
      end  
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/p_ms_helper.rb
module PMsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/santa_helper.rb
module SantaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/supervisions_helper.rb
module SupervisionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/delete.html.erb
<h1>Friendships#delete</h1>
<p>Find me in app/views/friendships/delete.html.erb</p>

app/views/friendships/edit.html.erb
<h1>Friendships#edit</h1>
<p>Find me in app/views/friendships/edit.html.erb</p>

app/views/friendships/index.html.erb
<div class="row darkgreen">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">
		<h3>Your Friends</h3>
			<table class="contents">
				<thead>
					<tr>
						<th>Name</th>
						<th>Options</th>
					</tr>
				</thead>
				<tbody>
					<% if @friends %>
					<% @friends.each do |person| %>
					<tr>
						<td><%= link_to "#{person.firstname} #{person.lastname}", user_path(:user_id => person.id) %></td>
						<td><%= link_to "Send Message", new_message_path(:user_id => person.id), :method => :post %> |
							<%= link_to "Remove", remove_friend_path(:user_id => person.id), :method => :delete %>
						</td>
					</tr>	
					<% end %>
					<% end %>
				</tbody>
			</table>
	</div>
	<div class="col-sm-4"></div>
</div>	

<div class="row green">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">

		<h3>Other Members of Our Community</h3>

		<table class="contents">
			<thead>
				<tr>
					<th>Name</th>
					<th>Options</th>
				</tr>
			</thead>
			<tbody>
				<% if @people %>
				<% @people.each do |person| %>
				<tr>
					<td><%= person.firstname %> <%= person.lastname %></td>
					<td><%= link_to "Add Friend", add_friend_path(:id => person.id), :method => :post %></td>
				</tr>	
				<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="col-sm-4"></div>
</div>

app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>

app/views/friendships/show.html.erb
<h1>Friendships#show</h1>
<p>Find me in app/views/friendships/show.html.erb</p>

app/views/friendships/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>